### ISSUE TITLE
TBO addon doesnot work

### ISSUE THREAD

**Issue by HarshEcka** [TheBeautifulOrc/TBO-Tree-Gen#1]
I have been trying to work with TBO addon with last few releases but however it does seems to work for me..Whenever I select the addon from panel in viewport the generate tree button doesnot seem to work...also if possible provide doc or video tutorial for this addon

**Comment by TheBeautifulOrc** [comment]
Hi, 
I'm actually thrilled to hear that someone stumbled across my Addon. However this project is absolutely unusable in it's current state (hence marked as Work-In-Progress). I'll try to finish it as soon as I can but until then all I can tell you is to stay patient. 😅
